# Generated by Django 2.0.4 on 2018-06-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('page_content', models.TextField()),
                ('page_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('sub_content', models.TextField()),
                ('sub_image', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='img_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.SubPage'),
        ),
    ]
