# Generated by Django 2.0.4 on 2018-06-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('cat_content', models.TextField()),
                ('cat_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_cat',
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='SubPage',
        ),
    ]
